force-app/main/default/objects/EmailServiceParser__mdt/EmailServiceParser__mdt.object-meta.xml
<CustomObject>
    <label>Email Service Parser</label>
    <pluralLabel>EmailServiceParsers</pluralLabel>
</CustomObject>

default/objects/EmailServiceParser__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

default/objects/EmailServiceParser__mdt/fields/Attributes__c.field-meta.xml
<CustomField>
    <fullName>Attributes__c</fullName>
    <label>Attributes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

objects/EmailServiceParser__mdt/fields/FromAddress__c.field-meta.xml
<CustomField>
    <fullName>FromAddress__c</fullName>
    <inlineHelpText>Allowed from address emails or domains separated by commas. FI: test@test.com,test2@test.com,s4g.com</inlineHelpText>
    <label>From Address</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailServiceParser__mdt/fields/RegexExpression__c.field-meta.xml
<CustomField>
    <fullName>RegexExpression__c</fullName>
    <inlineHelpText>JSON with the regular expressions that will be applied . FI: {&quot;subject&quot;:[&quot;[A-z]&quot;,&quot;[0-9]&quot;],&quot;body&quot;:[&quot;[1-9]&quot;],&quot;htmlbody&quot;:[&quot;[1-9]&quot;]}</inlineHelpText>
    <label>Regex Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

default/classes/EmailServiceParsersSelector_MDT.cls
public with sharing class EmailServiceParsersSelector_MDT {
    private final List <Schema.SObjectField> fields = new List <Schema.SObjectField> {
        EmailServiceParser__mdt.Id,
        EmailServiceParser__mdt.DeveloperName,
        EmailServiceParser__mdt.ApexClass__c,
        EmailServiceParser__mdt.Attributes__c,
        EmailServiceParser__mdt.FromAddress__c,
        EmailServiceParser__mdt.RegexExpression__c
    };

    private String condition;

    public List <EmailServiceParser__mdt> selectAll() {
        return (List <EmailServiceParser__mdt>)Database.query(getQuery());
    }

    private String getQuery() {
        return 'SELECT ' + getQueryFields() + ' FROM EmailServiceParser__mdt' + getCondition();
        //return EmailServiceParser__mdt.getAll().values();
    }

    private String getCondition() {
        return condition != null ? ' WHERE ' + condition : ''; 
    }

    private String getQueryFields() {
        String queryFields;
        for (Schema.SObjectField field : fields) {
            if (queryFields == null) {
                queryFields = field.getDescribe().getName();
            } else {
                queryFields += ', ' + field.getDescribe().getName();
            }
        }
        return queryFields;
    }


}