force-app/main/default/objects/EmailServiceParser__mdt/EmailServiceParser__mdt.object-meta.xml
<CustomObject>
    <label>Email Service Parser</label>
    <pluralLabel>EmailServiceParsers</pluralLabel>
</CustomObject>

default/objects/EmailServiceParser__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

default/objects/EmailServiceParser__mdt/fields/Attributes__c.field-meta.xml
<CustomField>
    <fullName>Attributes__c</fullName>
    <label>Attributes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

objects/EmailServiceParser__mdt/fields/FromAddress__c.field-meta.xml
<CustomField>
    <fullName>FromAddress__c</fullName>
    <inlineHelpText>Allowed from address emails or domains separated by commas. FI: test@test.com,test2@test.com,s4g.com</inlineHelpText>
    <label>From Address</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailServiceParser__mdt/fields/RegexExpression__c.field-meta.xml
<CustomField>
    <fullName>RegexExpression__c</fullName>
    <inlineHelpText>JSON with the regular expressions that will be applied . FI: {&quot;subject&quot;:[&quot;[A-z]&quot;,&quot;[0-9]&quot;],&quot;body&quot;:[&quot;[1-9]&quot;],&quot;htmlbody&quot;:[&quot;[1-9]&quot;]}</inlineHelpText>
    <label>Regex Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EmailServiceParserHelper.cls
public class EmailServiceParserHelper {
    public Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        List <EmailServiceParser__mdt> parsers;
        if (Test.isRunningTest()) {
            parsers = new List <EmailServiceParser__mdt> {new EmailServiceParser__mdt(ApexClass__c = 'TestEmailServiceParser.TestEmailService', Attributes__c = 'sample attributes', RegexExpression__c = '{"subject":["[A-z]"],"body":["[1-9]"],"htmlbody":["[1-9]"]}')};
        } else {
            parsers = new EmailServiceParsersSelector_MDT().selectAll();
        }
        MatcherResultInfoType regExResult;
        // try {
            for(EmailServiceParser__mdt parser : parsers) {
                List <Matcher> matcherList = new List <Matcher>();
                List <String> allowedFromAddress = parser.FromAddress__c != null ? parser.FromAddress__c.split(',') : null;
                if(isValidAddress(email.fromAddress, parser)) {
                    regExResult = processRegEx(email, parser);
                    if (regExResult.success) {
                        Type t = Type.forName(parser.ApexClass__c);
                        IEmailServiceParser serviceParser = (IEmailServiceParser)t.newInstance();
                        serviceParser.processEmail(email, regExResult.matcherList, parser.Attributes__c);
                    } else {
                        System.debug('Email does not match the specificied format');
                    }
                }
            }
        // }
        // catch (Exception e) {
        //     TODO: create exceptions handler
        //     System.debug('Error: ' + e.getMessage());
        //     System.debug('ErrorLine: ' + e.getLineNumber());
        //     return result;
        // }
        return result;
    }

    private Boolean isValidAddress(String fromAddress, EmailServiceParser__mdt config) {
        if (config.FromAddress__c != null) {
            List <String> allowedAdresses = config.FromAddress__c.split(',');
            for (String address : allowedAdresses) {
                if (address.contains('@') && address == fromAddress) {
                    return true;
                } else if (fromAddress.contains('@' + address)) {
                    return true;
                }
            }
        } else {
            return true;
        }
        return false;
    }

    private MatcherResultInfoType processRegEx(Messaging.InboundEmail email, EmailServiceParser__mdt config) {
        
        List <Matcher> matcherList = new List <Matcher>();
        if(config.RegexExpression__c == null) {return new MatcherResultInfoType(true, matcherList);}
        Map <String, List <String>> mapRegExp = (Map <String, List <String>>)JSON.deserializeStrict(config.RegexExpression__c, Map <String, List <String>>.class);
        for(String key : mapRegExp.keySet()) {
            List <Matcher> matcherListTemp;
            switch on key {
                when 'subject' {
                    matcherListTemp = executeRegEx(email.subject, mapRegExp.get(key));
                }
                when 'body' {
                    matcherListTemp = executeRegEx(email.plainTextBody, mapRegExp.get(key));
                }
                when 'htmlbody' {
                    matcherListTemp = executeRegEx(email.htmlBody, mapRegExp.get(key));
                }
            }
            if(matcherListTemp.size() == 0) {
                return new MatcherResultInfoType(false , null);
            } else {
                matcherList.addAll(matcherListTemp);
            }
        }
        return  new MatcherResultInfoType(true , matcherList); 
    }

    private List <Matcher> executeRegEx(String str, List <String> regExList) {
        List <Matcher> matcherList = new List <Matcher>();
        for(String regEx : regExList) {
            Matcher matcher = Pattern.compile(regEx).matcher(str);
            if(matcher.find()) {
                matcherList.add(matcher);
            } else {
                return new List <Matcher>();
            }
        }
        return matcherList;
    }

    private class MatcherResultInfoType {
        Boolean success;
        List <Matcher> matcherList;

        public MatcherResultInfoType(Boolean success, List <Matcher> matcherList) {
            this.success = success;
            this.matcherList = matcherList;
        }
    }
}