objects/Planet__c/Planet__c.object-meta.xml
<CustomObject>
    <label>Planet</label>
    <nameField>
        <label>Planet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planet_Code__mdt/Planet_Code__mdt.object-meta.xml
<CustomObject>
    <label>Planet Code</label>
    <pluralLabel>Planet Codes</pluralLabel>
</CustomObject>

objects/Planet_Code__mdt/fields/AccessCode__c.field-meta.xml
<CustomField>
    <fullName>AccessCode__c</fullName>
    <label>Access Code</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/Planet_Code__mdt/fields/External_id__c.field-meta.xml
<CustomField>
    <fullName>External_id__c</fullName>
    <label>External Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PlanetsServiceHelper.cls
public with sharing class PlanetsServiceHelper {
    public HttpResponse scanPlanet(Id planetId) {
        Planet__c planet = new PlanetsSelector(true).selectById(new Set <Id> {planetId})[0];
        Planet_Code__mdt planetCode = new PlanetCodesSelector_MDT().selectByExternalId(planet.External_Id__c);
        HTTPResponse res;
        if (planetCode != null) {
            try {
                Integer retries = 3;
                HttpRequest req = new HttpRequest();
                req.setEndpoint('callout:PlanetScan/scan/' + EncodingUtil.UrlEncode(planetCode.AccessCode__c,'UTF-8'));
                req.setMethod('GET');
                Http http = new Http();
                Integer cont = 0;
                Boolean success = false;
                do {
                    System.debug('entro');
                    res = http.send(req);
                    if (res.getStatusCode() == 200) {
                        success = true;
                    } else {
                        cont ++;
                    }
                } while(!success && cont < retries);
            } catch(Exception e) {
                System.debug(e.getMessage());
                System.debug(e.getLineNumber());
            }
        }
        return res;
    }
}